
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ambient-cluster1
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
- role: worker
networking:
  # the default CNI will not be installed
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet








  