kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ambient-cluster2
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
- role: worker
networking:
  podSubnet: "10.245.0.0/16"
  serviceSubnet: "10.97.0.0/16"